import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../../features/diagnosis/domain/entities/diagnosis_result.dart';
import '../../features/reports/domain/entities/diagnosis_report.dart';

/// Generates PDF reports and shares them via the system share sheet
/// (WhatsApp, Gmail, Bluetooth, etc. all appear automatically).
///
/// Used by all three roles:
///   - Farmer: shares their own scan result
///   - Extension Officer: shares a farmer's report with their notes
///   - Manager: shares any report in their district
class ReportShareService {
  static const _brandGreen = PdfColor.fromInt(0xFF4CAF50);
  static const _brandDark = PdfColor.fromInt(0xFF1B5E20);

  /// Share a fresh scan/diagnosis result (farmer flow).
  static Future<void> shareDiagnosis({
    required DiagnosisResult diagnosis,
    String? farmerName,
    String? farmerPhone,
    String? district,
    String? village,
  }) async {
    final pdf = await _buildDiagnosisPdf(
      diagnosis: diagnosis,
      farmerName: farmerName,
      farmerPhone: farmerPhone,
      district: district,
      village: village,
    );
    await _saveAndShare(
      pdf: pdf,
      filename:
          'MbewuSmart_Diagnosis_'
          '${_safe(diagnosis.cropType.name)}_'
          '${diagnosis.timestamp.millisecondsSinceEpoch}.pdf',
      subject: 'MbewuSmart Diagnosis — ${diagnosis.diagnosisName}',
      text:
          'Crop: ${diagnosis.cropType.name}\n'
          'Diagnosis: ${diagnosis.diagnosisName}\n'
          'Confidence: ${(diagnosis.confidence * 100).toStringAsFixed(0)}%\n'
          'Severity: ${diagnosis.severity.name}\n\n'
          'Generated by MbewuSmart.',
    );
  }

  /// Share an existing report from Firestore (officer / manager flow).
  /// Optional [officerNotes] / [managerNotes] are appended at the bottom.
  static Future<void> shareReport({
    required DiagnosisReport report,
    String? officerNotes,
    String? managerNotes,
  }) async {
    final pdf = await _buildReportPdf(
      report: report,
      officerNotes: officerNotes,
      managerNotes: managerNotes,
    );
    await _saveAndShare(
      pdf: pdf,
      filename:
          'MbewuSmart_Report_'
          '${_safe(report.farmerName)}_'
          '${report.timestamp.millisecondsSinceEpoch}.pdf',
      subject:
          'MbewuSmart Report — ${report.farmerName} (${report.diagnosisName})',
      text:
          'Farmer: ${report.farmerName}\n'
          'Phone: ${report.farmerPhone}\n'
          'Crop: ${report.cropType}\n'
          'Diagnosis: ${report.diagnosisName}\n'
          'Confidence: ${(report.confidence * 100).toStringAsFixed(0)}%\n'
          'District: ${report.district ?? "—"}\n\n'
          'Generated by MbewuSmart.',
    );
  }

  // ---------------------------------------------------------------------
  // PDF builders
  // ---------------------------------------------------------------------

  static Future<pw.Document> _buildDiagnosisPdf({
    required DiagnosisResult diagnosis,
    String? farmerName,
    String? farmerPhone,
    String? district,
    String? village,
  }) async {
    final pdf = pw.Document();
    final dateFmt = DateFormat('dd MMM yyyy, HH:mm');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          _header(
            subtitle: 'Crop Diagnosis Report',
            date: dateFmt.format(diagnosis.timestamp),
          ),
          pw.SizedBox(height: 20),

          // Farmer info (if available)
          if (farmerName != null || district != null || village != null) ...[
            _sectionTitle('Farmer Information'),
            if (farmerName != null) _kv('Name', farmerName),
            if (farmerPhone != null) _kv('Phone', farmerPhone),
            if (village != null) _kv('Village', village),
            if (district != null) _kv('District', district),
            pw.SizedBox(height: 16),
          ],

          // Diagnosis
          _sectionTitle('Diagnosis'),
          _kv('Crop', diagnosis.cropType.name),
          _kv('Issue', diagnosis.diagnosisName),
          if (diagnosis.diagnosisNameChichewa.isNotEmpty)
            _kv('Chichewa', diagnosis.diagnosisNameChichewa),
          _kv('Type', diagnosis.type.name),
          _kv('Severity', diagnosis.severity.name),
          _kv(
            'Confidence',
            '${(diagnosis.confidence * 100).toStringAsFixed(1)}%',
          ),
          if (diagnosis.scientificName != null &&
              diagnosis.scientificName!.isNotEmpty)
            _kv('Scientific name', diagnosis.scientificName!),
          pw.SizedBox(height: 16),

          // Causing factors
          if (diagnosis.causingFactors != null &&
              diagnosis.causingFactors!.isNotEmpty) ...[
            _sectionTitle('Causing Factors'),
            pw.Text(
              diagnosis.causingFactors!,
              style: const pw.TextStyle(fontSize: 11),
            ),
            pw.SizedBox(height: 16),
          ],

          // Treatment
          if (diagnosis.treatment != null &&
              diagnosis.treatment!.isNotEmpty) ...[
            _sectionTitle('Treatment'),
            pw.Text(
              diagnosis.treatment!,
              style: const pw.TextStyle(fontSize: 11),
            ),
            pw.SizedBox(height: 16),
          ],

          // Pesticide remedy
          if (diagnosis.pesticideRemedy != null &&
              diagnosis.pesticideRemedy!.isNotEmpty) ...[
            _sectionTitle('Recommended Pesticide'),
            pw.Text(
              diagnosis.pesticideRemedy!,
              style: const pw.TextStyle(fontSize: 11),
            ),
            pw.SizedBox(height: 16),
          ],

          // Prevention
          if (diagnosis.prevention != null &&
              diagnosis.prevention!.isNotEmpty) ...[
            _sectionTitle('Prevention'),
            pw.Text(
              diagnosis.prevention!,
              style: const pw.TextStyle(fontSize: 11),
            ),
            pw.SizedBox(height: 16),
          ],

          // Recommendation
          if (diagnosis.recommendation != null &&
              diagnosis.recommendation!.isNotEmpty) ...[
            _sectionTitle('Recommendation'),
            pw.Text(
              diagnosis.recommendation!,
              style: const pw.TextStyle(fontSize: 11),
            ),
            pw.SizedBox(height: 16),
          ],

          // Location
          if (diagnosis.locationName != null &&
              diagnosis.locationName!.isNotEmpty) ...[
            _sectionTitle('Location'),
            _kv('Place', diagnosis.locationName!),
            if (diagnosis.latitude != null && diagnosis.longitude != null)
              _kv(
                'Coordinates',
                '${diagnosis.latitude!.toStringAsFixed(4)}, ${diagnosis.longitude!.toStringAsFixed(4)}',
              ),
          ],

          pw.SizedBox(height: 30),
          _footer(),
        ],
      ),
    );

    return pdf;
  }

  static Future<pw.Document> _buildReportPdf({
    required DiagnosisReport report,
    String? officerNotes,
    String? managerNotes,
  }) async {
    final pdf = pw.Document();
    final dateFmt = DateFormat('dd MMM yyyy, HH:mm');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          _header(
            subtitle: 'Farmer Report',
            date: dateFmt.format(report.timestamp),
          ),
          pw.SizedBox(height: 20),

          _sectionTitle('Farmer'),
          _kv('Name', report.farmerName),
          _kv('Phone', report.farmerPhone),
          if (report.district != null && report.district!.isNotEmpty)
            _kv('District', report.district!),
          if (report.placeName != null && report.placeName!.isNotEmpty)
            _kv('Place', report.placeName!),
          pw.SizedBox(height: 16),

          _sectionTitle('Diagnosis'),
          _kv('Crop', report.cropType),
          _kv('Issue', report.diagnosisName),
          _kv('Confidence', '${(report.confidence * 100).toStringAsFixed(1)}%'),
          _kv('Status', report.status),
          pw.SizedBox(height: 16),

          if (report.notes.trim().isNotEmpty) ...[
            _sectionTitle('Notes from Report'),
            pw.Text(report.notes, style: const pw.TextStyle(fontSize: 11)),
            pw.SizedBox(height: 16),
          ],

          if (officerNotes != null && officerNotes.trim().isNotEmpty) ...[
            _sectionTitle('Extension Officer Notes'),
            pw.Text(officerNotes, style: const pw.TextStyle(fontSize: 11)),
            pw.SizedBox(height: 16),
          ],

          if (managerNotes != null && managerNotes.trim().isNotEmpty) ...[
            _sectionTitle('Agricultural Manager Notes'),
            pw.Text(managerNotes, style: const pw.TextStyle(fontSize: 11)),
            pw.SizedBox(height: 16),
          ],

          if (report.latitude != null && report.longitude != null) ...[
            _sectionTitle('GPS Coordinates'),
            pw.Text(
              '${report.latitude!.toStringAsFixed(5)}, '
              '${report.longitude!.toStringAsFixed(5)}',
              style: const pw.TextStyle(fontSize: 11),
            ),
          ],

          pw.SizedBox(height: 30),
          _footer(),
        ],
      ),
    );

    return pdf;
  }

  // ---------------------------------------------------------------------
  // Save + share
  // ---------------------------------------------------------------------

  static Future<void> _saveAndShare({
    required pw.Document pdf,
    required String filename,
    required String subject,
    required String text,
  }) async {
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$filename');
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      subject: subject,
      text: text,
    );
  }

  // ---------------------------------------------------------------------
  // PDF helper widgets
  // ---------------------------------------------------------------------

  static pw.Widget _header({required String subtitle, required String date}) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: _brandGreen,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'MbewuSmart',
                style: pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                subtitle,
                style: const pw.TextStyle(color: PdfColors.white, fontSize: 13),
              ),
            ],
          ),
          pw.Text(
            date,
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 10),
          ),
        ],
      ),
    );
  }

  static pw.Widget _sectionTitle(String text) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 13,
          fontWeight: pw.FontWeight.bold,
          color: _brandDark,
        ),
      ),
    );
  }

  static pw.Widget _kv(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 110,
            child: pw.Text(
              label,
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 11)),
          ),
        ],
      ),
    );
  }

  static pw.Widget _footer() {
    return pw.Column(
      children: [
        pw.Divider(),
        pw.SizedBox(height: 4),
        pw.Text(
          'Generated by MbewuSmart — AI-powered crop diagnosis for Malawian farmers.',
          style: pw.TextStyle(
            fontSize: 9,
            color: PdfColors.grey700,
            fontStyle: pw.FontStyle.italic,
          ),
          textAlign: pw.TextAlign.center,
        ),
      ],
    );
  }

  static String _safe(String s) => s.replaceAll(RegExp(r'[^A-Za-z0-9_]'), '_');
}
